#!/bin/bash
pdflatex main.beamer.tex
pdflatex main.beamer.tex
pdflatex main.notes.tex
pdflatex main.notes.tex
pdflatex main.article.tex
pdflatex main.article.tex
rm *.aux *.log *.out *.toc *.nav *.snm *.vrb
