#!/bin/bash
pdflatex main_beamer.tex
pdflatex main_beamer.tex
pdflatex main_notes.tex
pdflatex main_notes.tex
pdflatex main_article.tex
pdflatex main_article.tex
pdflatex main_handout.tex
pdflatex main_handout.tex
pdflatex handout_entregable.tex
pdflatex handout_entregable.tex
rm *.aux *.log *.out *.toc *.nav *.snm *.vrb
